#  set keymap
setxkbmap pl
#  japanese input
export GTK_IM_MODULE='fcitx'
export QT_IM_MODULE='fcitx'
#uim-xim &
export XMODIFIERS='@im=fcitx'
#  default
exec fcitx &
exec xbanish &
#exec window manager 
#simple_status_monitor.sh &
exec dwm


