#  set keymap
setxkbmap pl
#  japanese input
export GTK_IM_MODULE='fcitx'
export QT_IM_MODULE='fcitx'
export XMODIFIERS='@im=fcitx'
#  default
exec fcitx &
exec xbanish &
exec sxhkd &
#exec window manager 
exec slstatus &
exec dwm


